Repository woowa-techcamp-2022/web-moneybook-2, pull requests merged in 2022-07, with the labels that each got.

#2 Feat/project setup
  .eslintrc.js
  .gitignore
  .gitmessage
  babel.config.js
  client/index.html
  client/src/index.js
  client/src/styles/styles.css
  package-lock.json
  package.json
  prettier.config.js
  server/app.js
  server/config/index.js
  server/index.js
  server/middlewares/webpack.middleware.js
  webpack.config.js
Labels: feature

#9 [Feature] 백엔드 Service 구현
  server/common/custom-exception.js
  server/models/payment-method.model.js
  server/models/transaction-history.model.js
  server/services/category.service.js
  server/services/payment-method.service.js
  server/services/transaction-history.service.js
  server/utils/date.util.js
Labels: feature, backend

#10 [Style] babel-node 적용
  package-lock.json
  package.json
  server/app.js
  server/common/custom-exception.js
  server/config/index.js
  server/db/index.js
  server/index.js
  server/middlewares/webpack.middleware.js
  server/models/category.model.js
  server/models/payment-method.model.js
  server/models/transaction-history.model.js
  server/services/category.service.js
  server/services/payment-method.service.js
  server/services/transaction-history.service.js
  server/utils/date.util.js
Labels: backend, style

#15 [Feature] 백엔드 Controller, Router 개발
  server/app.js
  server/controllers/category.controller.js
  server/controllers/payment-method.controller.js
  server/controllers/transaction-history.controller.js
  server/models/category.model.js
  server/models/payment-method.model.js
  server/models/transaction-history.model.js
  server/routers/api.router.js
  server/routers/category.router.js
  server/routers/payment-method.router.js
  server/routers/transaction-history.router.js
  server/services/category.service.js
  server/services/payment-method.service.js
  server/services/transaction-history.service.js
Labels: feature, backend

#17 [Feature] Base Component 추가
  client/src/base/component.js
Labels: feature, frontend

#20 [Feature] Routing 기본 구조 추가
  client/src/base/router.js
  client/src/components/Header.js
  client/src/index.js
  client/src/pages/CalendarPage.js
  client/src/pages/MainPage.js
  client/src/pages/NotFoundPage.js
  client/src/pages/StatisticsPage.js
Labels: feature, frontend

#22 [Feature] Gloabl Style 추가 및 적용
  client/src/index.js
  client/src/styles/fonts.css
  client/src/styles/global.css
  client/src/styles/normalize.css
  client/src/styles/styles.css
Labels: feature, frontend

#23 [Feature] Model 추가
  client/src/base/observable.js
  client/src/constants/keys.js
  client/src/model/index.js
  client/src/pages/CalendarPage.js
  client/src/pages/MainPage.js
  client/src/pages/NotFoundPage.js
  client/src/pages/StatisticsPage.js
Labels: feature, frontend

#26 [Feature] Header 컴포넌트 구현 및 store, controller 구현
  client/src/base/component.js
  client/src/base/observable.js
  client/src/components/Header.js
  client/src/components/Header/HeaderCalendar/index.js
  client/src/components/Header/Logo/index.js
  client/src/components/Header/Navigation/index.js
  client/src/components/Header/index.css
  client/src/components/Header/index.js
  client/src/constants/keys.js
  client/src/controller/index.js
  client/src/index.js
  client/src/model/index.js
  client/src/store/index.js
  client/src/styles/global.css
  client/src/utils/api-util.js
  client/src/utils/date-util.js
Labels: feature, frontend

#30 [Feature] Backend Exception 관련 처리 추가
  server/constants/error-message.constant.js
  server/constants/status-code.constant.js
  server/controllers/category.controller.js
  server/controllers/payment-method.controller.js
  server/controllers/transaction-history.controller.js
  server/db/query.js
  server/index.js
  server/middlewares/exception-handler.middleware.js
  server/models/category.model.js
  server/models/payment-method.model.js
  server/models/transaction-history.model.js
  server/routers/api.router.js
  server/services/category.service.js
  server/services/payment-method.service.js
  server/services/transaction-history.service.js
Labels: feature, backend

#29 [Feature] 메인페이지 InputBar 구현
  client/src/base/component.js
  client/src/components/Header/HeaderCalendar/index.js
  client/src/components/Header/Logo/index.js
  client/src/components/Header/index.js
  client/src/components/InputBar/CategoryInput/index.js
  client/src/components/InputBar/ConfirmButton/index.js
  client/src/components/InputBar/DateInput/index.js
  client/src/components/InputBar/Dropdown/index.js
  client/src/components/InputBar/MoneyInput/index.js
  client/src/components/InputBar/PaymentMethodInput/index.js
  client/src/components/InputBar/TitleInput/index.js
  client/src/components/InputBar/index.css
  client/src/components/InputBar/index.js
  client/src/constants/keys.js
  client/src/controller/index.js
  client/src/index.js
  client/src/pages/MainPage.js
  client/src/pages/page.css
  client/src/store/index.js
  client/src/styles/global.css
  client/src/utils/date-util.js
Labels: feature, frontend

#35 [Feature] 결제수단 추가 및 삭제 로직 추가
  client/index.html
  client/src/base/component.js
  client/src/components/InputBar/CategoryInput/CategoryList/index.js
  client/src/components/InputBar/CategoryInput/index.js
  client/src/components/InputBar/DateInput/index.js
  client/src/components/InputBar/Dropdown/index.js
  client/src/components/InputBar/PaymentMethodInput/PaymentMethodList/index.js
  client/src/components/InputBar/PaymentMethodInput/index.js
  client/src/components/InputBar/index.css
  client/src/components/Modal/index.css
  client/src/components/Modal/index.js
  client/src/constants/actions.js
  client/src/constants/messages.js
  client/src/controller/index.js
  client/src/utils/api-util.js
  client/src/utils/date-util.js
Labels: feature, frontend, pair

#32 [Feature] SVG 관련 기능 추가
  client/src/assets/calendar.svg
  client/src/assets/check.svg
  client/src/assets/chevron-left.svg
  client/src/assets/chevron-right.svg
  client/src/assets/file.svg
  client/src/assets/statistics.svg
  client/src/components/Header/HeaderCalendar/index.js
  client/src/components/Header/Navigation/index.js
  client/src/components/Header/index.css
  package-lock.json
  package.json
  webpack.config.js
Labels: feature, frontend

#38 [Feature] API 관련 응답 수정
  server/controllers/payment-method.controller.js
  server/controllers/transaction-history.controller.js
  server/models/payment-method.model.js
  server/models/transaction-history.model.js
  server/services/payment-method.service.js
  server/services/transaction-history.service.js
Labels: feature, backend

#39 [Feature] InputBar 관련 스타일 추가 및 수정
  client/src/assets/delete.svg
  client/src/assets/minus.svg
  client/src/assets/plus.svg
  client/src/components/Header/index.css
  client/src/components/InputBar/CategoryInput/CategoryList/index.js
  client/src/components/InputBar/CategoryInput/index.js
  client/src/components/InputBar/DateInput/index.js
  client/src/components/InputBar/Dropdown/index.js
  client/src/components/InputBar/MoneyInput/index.js
  client/src/components/InputBar/PaymentMethodInput/PaymentMethodList/index.js
  client/src/components/InputBar/PaymentMethodInput/index.js
  client/src/components/InputBar/SubmitButton/index.js
  client/src/components/InputBar/TitleInput/index.js
  client/src/components/InputBar/index.css
  client/src/components/InputBar/index.js
  client/src/components/Modal/index.css
  client/src/components/Modal/index.js
  client/src/constants/messages.js
  client/src/controller/index.js
  client/src/styles/global.css
  webpack.config.js
Labels: feature, frontend, refactor

#41 [Feature] 결제내역 리스트 구현 #34
  client/src/components/Header/HeaderCalendar/index.js
  client/src/components/InputBar/SubmitButton/index.js
  client/src/components/TransactionHistoryList/ListContent/EditingOverlay/index.js
  client/src/components/TransactionHistoryList/ListContent/ListItem/ListItemCell/index.js
  client/src/components/TransactionHistoryList/ListContent/ListItem/ListItemHeader/index.js
  client/src/components/TransactionHistoryList/ListContent/ListItem/index.js
  client/src/components/TransactionHistoryList/ListContent/index.js
  client/src/components/TransactionHistoryList/ListHeader/ListFilter/index.js
  client/src/components/TransactionHistoryList/ListHeader/index.js
  client/src/components/TransactionHistoryList/index.css
  client/src/components/TransactionHistoryList/index.js
  client/src/constants/keys.js
  client/src/controller/index.js
  client/src/index.js
  client/src/pages/MainPage.js
  client/src/utils/api-util.js
  client/src/utils/date-util.js
  client/src/utils/transaction-history-util.js
Labels: feature, frontend

#45 [Feature] Calendar 페이지 추가
  client/src/components/Calendar/CalendarBody/index.js
  client/src/components/Calendar/CalendarFooter/index.js
  client/src/components/Calendar/CalendarHeader/index.js
  client/src/components/Calendar/index.css
  client/src/components/Calendar/index.js
  client/src/pages/CalendarPage.js
  client/src/styles/global.css
  client/src/utils/date-util.js
  client/src/utils/transaction-history-util.js
Labels: feature, frontend

#46 [Feature] 카테고리별 총 지출 API 추가
  server/controllers/category.controller.js
  server/controllers/transaction-history.controller.js
  server/models/transaction-history.model.js
  server/routers/transaction-history.router.js
  server/services/transaction-history.service.js
  server/utils/date.util.js
Labels: feature, backend

#47 [Feature] Statistics 페이지 추가
  client/src/base/chart.js
  client/src/components/Header/index.js
  client/src/components/StatisticsBoard/AdditionalInfoBoard/AdditionalInfoList/index.js
  client/src/components/StatisticsBoard/AdditionalInfoBoard/LineChartBoard/LineChart/index.js
  client/src/components/StatisticsBoard/AdditionalInfoBoard/LineChartBoard/index.css
  client/src/components/StatisticsBoard/AdditionalInfoBoard/LineChartBoard/index.js
  client/src/components/StatisticsBoard/AdditionalInfoBoard/index.js
  client/src/components/StatisticsBoard/DoughnutChartBoard/DoughnutChart/index.js
  client/src/components/StatisticsBoard/DoughnutChartBoard/SpentList/index.js
  client/src/components/StatisticsBoard/DoughnutChartBoard/index.js
  client/src/components/StatisticsBoard/index.css
  client/src/components/StatisticsBoard/index.js
  client/src/components/TransactionHistoryList/ListContent/ListItem/ListItemHeader/index.js
  client/src/components/TransactionHistoryList/ListContent/ListItem/index.js
  client/src/constants/keys.js
  client/src/controller/index.js
  client/src/index.js
  client/src/pages/MainPage.js
  client/src/pages/StatisticsPage.js
  client/src/pages/page.css
  client/src/styles/global.css
  client/src/utils/api-util.js
  client/src/utils/chart-util.js
  client/src/utils/transaction-history-util.js
  server/models/transaction-history.model.js
Labels: feature, frontend, pair

#51 [Feature] 데이터베이스 테이블 관련 기능 추가
  server/db/feed.js
  server/db/index.js
  server/db/init.js
  server/models/category.model.js
  server/models/payment-method.model.js
Labels: feature, backend

#52 [Fix] 달력 버그 픽스
  client/src/controller/index.js
  client/src/utils/date-util.js
Labels: bug, frontend

#53 [FIX] INNER JOIN을 LEFT JOIN으로 변경
  server/models/transaction-history.model.js
Labels: backend, fix

#55 [Fix] 메인페이지 버그 픽스 및 UX 개선
  client/src/assets/empty.png
  client/src/components/InputBar/CategoryInput/CategoryList/index.js
  client/src/components/InputBar/CategoryInput/index.js
  client/src/components/InputBar/Dropdown/index.js
  client/src/components/InputBar/index.js
  client/src/components/StatisticsBoard/AdditionalInfoBoard/LineChartBoard/index.js
  client/src/components/StatisticsBoard/DoughnutChartBoard/DoughnutChart/index.js
  client/src/components/StatisticsBoard/DoughnutChartBoard/index.js
  client/src/components/TransactionHistoryList/ListContent/EmptyItem/index.js
  client/src/components/TransactionHistoryList/ListContent/ListItem/ListItemCell/index.js
  client/src/components/TransactionHistoryList/ListContent/index.js
  client/src/components/TransactionHistoryList/index.css
  client/src/components/TransactionHistoryList/index.js
  client/src/controller/index.js
  client/src/pages/MainPage.js
  client/src/utils/chart-util.js
Labels: bug, feature, frontend

#56 [Feature] 메인페이지 스타일 최적화 및 수정
  client/src/assets/chevron-down.svg
  client/src/base/router.js
  client/src/components/Header/Navigation/index.js
  client/src/components/Header/index.css
  client/src/components/Header/index.js
  client/src/components/InputBar/CategoryInput/index.js
  client/src/components/InputBar/Dropdown/index.js
  client/src/components/InputBar/PaymentMethodInput/index.js
  client/src/components/InputBar/index.css
  client/src/components/InputBar/index.js
  client/src/components/TransactionHistoryList/ListContent/EditingOverlay/index.js
  client/src/components/TransactionHistoryList/ListContent/ListItem/ListItemHeader/index.js
  client/src/components/TransactionHistoryList/ListContent/index.js
  client/src/components/TransactionHistoryList/ListHeader/ListFilter/index.js
  client/src/components/TransactionHistoryList/ListHeader/index.js
  client/src/components/TransactionHistoryList/index.css
  client/src/constants/page.js
  client/src/index.js
  client/src/pages/CalendarPage.js
  client/src/pages/MainPage.js
  client/src/pages/NotFoundPage.js
  client/src/pages/StatisticsPage.js
  client/src/styles/global.css
Labels: feature, frontend, fix

#59 feat: NotFoundPage 추가
  client/src/pages/NotFoundPage.js
  client/src/styles/global.css
Labels: feature, frontend

#60 [DOCS] README 작성
  README.md
  contents/calendar.jpg
  contents/main.jpg
  contents/statistics.jpg
  contents/woowa-moneybook.png
Labels: documentation
